# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'duplicateMethod.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_duplicateMethodChoice(object):
    def setupUi(self, duplicateMethodChoice):
        duplicateMethodChoice.setObjectName("duplicateMethodChoice")
        duplicateMethodChoice.resize(516, 362)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(duplicateMethodChoice.sizePolicy().hasHeightForWidth())
        duplicateMethodChoice.setSizePolicy(sizePolicy)
        self.layoutWidget = QtWidgets.QWidget(duplicateMethodChoice)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 1, 502, 347))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.simple_copy_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.simple_copy_checkbox.setFont(font)
        self.simple_copy_checkbox.setObjectName("simple_copy_checkbox")
        self.verticalLayout.addWidget(self.simple_copy_checkbox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.interpolate_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.interpolate_checkbox.setFont(font)
        self.interpolate_checkbox.setObjectName("interpolate_checkbox")
        self.verticalLayout.addWidget(self.interpolate_checkbox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.lucas_kanade_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lucas_kanade_checkbox.setFont(font)
        self.lucas_kanade_checkbox.setObjectName("lucas_kanade_checkbox")
        self.verticalLayout.addWidget(self.lucas_kanade_checkbox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gunner_farnerback_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gunner_farnerback_checkbox.setFont(font)
        self.gunner_farnerback_checkbox.setObjectName("gunner_farnerback_checkbox")
        self.verticalLayout.addWidget(self.gunner_farnerback_checkbox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.scopeComboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scopeComboBox.setFont(font)
        self.scopeComboBox.setMaxVisibleItems(3)
        self.scopeComboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.scopeComboBox.setObjectName("scopeComboBox")
        self.verticalLayout_3.addWidget(self.scopeComboBox)
        spacerItem9 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        spacerItem10 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)

        self.retranslateUi(duplicateMethodChoice)
        self.buttonBox.rejected.connect(duplicateMethodChoice.reject)
        self.buttonBox.accepted.connect(duplicateMethodChoice.accept)
        QtCore.QMetaObject.connectSlotsByName(duplicateMethodChoice)

    def retranslateUi(self, duplicateMethodChoice):
        _translate = QtCore.QCoreApplication.translate
        duplicateMethodChoice.setWindowTitle(_translate("duplicateMethodChoice", "duplicate method selection"))
        self.label_11.setText(_translate("duplicateMethodChoice", "Choose duplicate method"))
        self.simple_copy_checkbox.setText(_translate("duplicateMethodChoice", "Simple copy"))
        self.interpolate_checkbox.setText(_translate("duplicateMethodChoice", "Interpolate"))
        self.lucas_kanade_checkbox.setText(_translate("duplicateMethodChoice", "Lucas-Kanade"))
        self.gunner_farnerback_checkbox.setText(_translate("duplicateMethodChoice", "Gunner-Farneback"))
        self.label_10.setText(_translate("duplicateMethodChoice", "Scope of change"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    duplicateMethodChoice = QtWidgets.QDialog()
    ui = Ui_duplicateMethodChoice()
    ui.setupUi(duplicateMethodChoice)
    duplicateMethodChoice.show()
    sys.exit(app.exec_())

