# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lucasKanadeParam.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_lucasKanadeParam(object):
    def setupUi(self, lucasKanadeParam):
        lucasKanadeParam.setObjectName("lucasKanadeParam")
        lucasKanadeParam.resize(530, 405)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(lucasKanadeParam.sizePolicy().hasHeightForWidth())
        lucasKanadeParam.setSizePolicy(sizePolicy)
        self.widget = QtWidgets.QWidget(lucasKanadeParam)
        self.widget.setGeometry(QtCore.QRect(20, 20, 500, 356))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.ShiTomasiMaxCorner = QtWidgets.QLineEdit(self.widget)
        self.ShiTomasiMaxCorner.setInputMask("")
        self.ShiTomasiMaxCorner.setObjectName("ShiTomasiMaxCorner")
        self.horizontalLayout.addWidget(self.ShiTomasiMaxCorner)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.ShiTomasiQualityLevel = QtWidgets.QLineEdit(self.widget)
        self.ShiTomasiQualityLevel.setObjectName("ShiTomasiQualityLevel")
        self.horizontalLayout_2.addWidget(self.ShiTomasiQualityLevel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.ShiTomasiMinDistance = QtWidgets.QLineEdit(self.widget)
        self.ShiTomasiMinDistance.setObjectName("ShiTomasiMinDistance")
        self.horizontalLayout_3.addWidget(self.ShiTomasiMinDistance)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.ShiTomasiBlockSize = QtWidgets.QLineEdit(self.widget)
        self.ShiTomasiBlockSize.setObjectName("ShiTomasiBlockSize")
        self.horizontalLayout_4.addWidget(self.ShiTomasiBlockSize)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(26, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        spacerItem2 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.LucasKanadeWindowSize = QtWidgets.QLineEdit(self.widget)
        self.LucasKanadeWindowSize.setObjectName("LucasKanadeWindowSize")
        self.horizontalLayout_5.addWidget(self.LucasKanadeWindowSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.LucasKanadeMaxLevel = QtWidgets.QLineEdit(self.widget)
        self.LucasKanadeMaxLevel.setObjectName("LucasKanadeMaxLevel")
        self.horizontalLayout_6.addWidget(self.LucasKanadeMaxLevel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.LucasKanadeCriteria = QtWidgets.QLineEdit(self.widget)
        self.LucasKanadeCriteria.setObjectName("LucasKanadeCriteria")
        self.horizontalLayout_7.addWidget(self.LucasKanadeCriteria)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.label_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.scopeComboBox = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scopeComboBox.setFont(font)
        self.scopeComboBox.setMaxVisibleItems(3)
        self.scopeComboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.scopeComboBox.setObjectName("scopeComboBox")
        self.verticalLayout_3.addWidget(self.scopeComboBox)
        spacerItem8 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)

        self.retranslateUi(lucasKanadeParam)
        self.buttonBox.accepted.connect(lucasKanadeParam.accept)
        self.buttonBox.rejected.connect(lucasKanadeParam.reject)
        QtCore.QMetaObject.connectSlotsByName(lucasKanadeParam)

    def retranslateUi(self, lucasKanadeParam):
        _translate = QtCore.QCoreApplication.translate
        lucasKanadeParam.setWindowTitle(_translate("lucasKanadeParam", "Lucas Kanade parameters"))
        self.label.setText(_translate("lucasKanadeParam", "   Shi Tomasi corner parameters"))
        self.label_3.setText(_translate("lucasKanadeParam", "max corners"))
        self.label_4.setText(_translate("lucasKanadeParam", "quality level"))
        self.label_5.setText(_translate("lucasKanadeParam", "min distance"))
        self.label_6.setText(_translate("lucasKanadeParam", "block size     "))
        self.label_2.setText(_translate("lucasKanadeParam", "   Lucas Kanade Flow Parameters"))
        self.label_7.setText(_translate("lucasKanadeParam", "  window size   "))
        self.label_8.setText(_translate("lucasKanadeParam", "    max level     "))
        self.label_9.setText(_translate("lucasKanadeParam", "        criteria      "))
        self.label_10.setText(_translate("lucasKanadeParam", "Scope of change"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    lucasKanadeParam = QtWidgets.QDialog()
    ui = Ui_lucasKanadeParam()
    ui.setupUi(lucasKanadeParam)
    lucasKanadeParam.show()
    sys.exit(app.exec_())

