# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'My6thWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1547, 899)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1547, 899))
        MainWindow.setMaximumSize(QtCore.QSize(1547, 899))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(False)
        self.MyWindows = QtWidgets.QWidget(MainWindow)
        self.MyWindows.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MyWindows.sizePolicy().hasHeightForWidth())
        self.MyWindows.setSizePolicy(sizePolicy)
        self.MyWindows.setMinimumSize(QtCore.QSize(1547, 858))
        self.MyWindows.setMaximumSize(QtCore.QSize(1547, 858))
        self.MyWindows.setBaseSize(QtCore.QSize(1818, 890))
        self.MyWindows.setObjectName("MyWindows")
        self.layoutWidget = QtWidgets.QWidget(self.MyWindows)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1516, 850))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBar = QtWidgets.QHBoxLayout()
        self.toolBar.setObjectName("toolBar")
        self.PicklePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.PicklePushButton.setObjectName("PicklePushButton")
        self.toolBar.addWidget(self.PicklePushButton)
        self.UnpicklePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.UnpicklePushButton.setObjectName("UnpicklePushButton")
        self.toolBar.addWidget(self.UnpicklePushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolBar.addItem(spacerItem)
        self.RemovePushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemovePushButton.sizePolicy().hasHeightForWidth())
        self.RemovePushButton.setSizePolicy(sizePolicy)
        self.RemovePushButton.setMinimumSize(QtCore.QSize(70, 30))
        self.RemovePushButton.setMaximumSize(QtCore.QSize(70, 30))
        self.RemovePushButton.setObjectName("RemovePushButton")
        self.toolBar.addWidget(self.RemovePushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolBar.addItem(spacerItem1)
        self.DuplicatePushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DuplicatePushButton.sizePolicy().hasHeightForWidth())
        self.DuplicatePushButton.setSizePolicy(sizePolicy)
        self.DuplicatePushButton.setMinimumSize(QtCore.QSize(70, 30))
        self.DuplicatePushButton.setMaximumSize(QtCore.QSize(70, 30))
        self.DuplicatePushButton.setObjectName("DuplicatePushButton")
        self.toolBar.addWidget(self.DuplicatePushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolBar.addItem(spacerItem2)
        self.RollbackPushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RollbackPushButton.sizePolicy().hasHeightForWidth())
        self.RollbackPushButton.setSizePolicy(sizePolicy)
        self.RollbackPushButton.setMinimumSize(QtCore.QSize(70, 30))
        self.RollbackPushButton.setMaximumSize(QtCore.QSize(70, 30))
        self.RollbackPushButton.setObjectName("RollbackPushButton")
        self.toolBar.addWidget(self.RollbackPushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolBar.addItem(spacerItem3)
        self.ExtractPushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExtractPushButton.sizePolicy().hasHeightForWidth())
        self.ExtractPushButton.setSizePolicy(sizePolicy)
        self.ExtractPushButton.setMinimumSize(QtCore.QSize(70, 30))
        self.ExtractPushButton.setMaximumSize(QtCore.QSize(70, 30))
        self.ExtractPushButton.setObjectName("ExtractPushButton")
        self.toolBar.addWidget(self.ExtractPushButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolBar.addItem(spacerItem4)
        self.showvideoButton = QtWidgets.QPushButton(self.layoutWidget)
        self.showvideoButton.setMinimumSize(QtCore.QSize(70, 30))
        self.showvideoButton.setMaximumSize(QtCore.QSize(70, 30))
        self.showvideoButton.setObjectName("showvideoButton")
        self.toolBar.addWidget(self.showvideoButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolBar.addItem(spacerItem5)
        self.ClearSelectionPushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearSelectionPushButton.sizePolicy().hasHeightForWidth())
        self.ClearSelectionPushButton.setSizePolicy(sizePolicy)
        self.ClearSelectionPushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.ClearSelectionPushButton.setMaximumSize(QtCore.QSize(90, 30))
        self.ClearSelectionPushButton.setObjectName("ClearSelectionPushButton")
        self.toolBar.addWidget(self.ClearSelectionPushButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolBar.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.toolBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageGraphSlider = QtWidgets.QVBoxLayout()
        self.imageGraphSlider.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.imageGraphSlider.setObjectName("imageGraphSlider")
        self.matplotlibwidget = QtWidgets.QWidget(self.layoutWidget)
        self.matplotlibwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibwidget.sizePolicy().hasHeightForWidth())
        self.matplotlibwidget.setSizePolicy(sizePolicy)
        self.matplotlibwidget.setMinimumSize(QtCore.QSize(600, 400))
        self.matplotlibwidget.setMaximumSize(QtCore.QSize(600, 400))
        self.matplotlibwidget.setBaseSize(QtCore.QSize(600, 400))
        self.matplotlibwidget.setObjectName("matplotlibwidget")
        self.imageGraphSlider.addWidget(self.matplotlibwidget)
        self.sliderlayout = QtWidgets.QHBoxLayout()
        self.sliderlayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.sliderlayout.setObjectName("sliderlayout")
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sliderlayout.addItem(spacerItem7)
        self.ShowImageRadioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.ShowImageRadioButton.setMinimumSize(QtCore.QSize(10, 20))
        self.ShowImageRadioButton.setMaximumSize(QtCore.QSize(20, 20))
        self.ShowImageRadioButton.setText("")
        self.ShowImageRadioButton.setChecked(True)
        self.ShowImageRadioButton.setObjectName("ShowImageRadioButton")
        self.sliderlayout.addWidget(self.ShowImageRadioButton)
        self.picture_slider = QtWidgets.QSlider(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture_slider.sizePolicy().hasHeightForWidth())
        self.picture_slider.setSizePolicy(sizePolicy)
        self.picture_slider.setMinimumSize(QtCore.QSize(525, 25))
        self.picture_slider.setOrientation(QtCore.Qt.Horizontal)
        self.picture_slider.setObjectName("picture_slider")
        self.sliderlayout.addWidget(self.picture_slider)
        spacerItem8 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.sliderlayout.addItem(spacerItem8)
        self.imageGraphSlider.addLayout(self.sliderlayout)
        self.verticalLayout.addLayout(self.imageGraphSlider)
        self.treeView = QtWidgets.QTreeView(self.layoutWidget)
        self.treeView.setMinimumSize(QtCore.QSize(600, 350))
        self.treeView.setMaximumSize(QtCore.QSize(600, 350))
        self.treeView.setBaseSize(QtCore.QSize(600, 400))
        self.treeView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.treeView.setRootIsDecorated(True)
        self.treeView.setSortingEnabled(False)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listView = QtWidgets.QListView(self.layoutWidget)
        self.listView.setMinimumSize(QtCore.QSize(400, 200))
        self.listView.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.listView.setFont(font)
        self.listView.setObjectName("listView")
        self.verticalLayout_2.addWidget(self.listView)
        self.tableView = QtWidgets.QTableView(self.layoutWidget)
        self.tableView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(900, 600))
        self.tableView.setMaximumSize(QtCore.QSize(900, 1000))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableView.setFont(font)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setGridStyle(QtCore.Qt.NoPen)
        self.tableView.setSortingEnabled(False)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView.horizontalHeader().setSortIndicatorShown(False)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(True)
        self.tableView.verticalHeader().setCascadingSectionResizes(True)
        self.tableView.verticalHeader().setHighlightSections(True)
        self.tableView.verticalHeader().setSortIndicatorShown(False)
        self.tableView.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableView)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.MyWindows)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1547, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuPreferences = QtWidgets.QMenu(self.menuEdit)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menuToggle_Duplicate_Mode = QtWidgets.QMenu(self.menuPreferences)
        self.menuToggle_Duplicate_Mode.setObjectName("menuToggle_Duplicate_Mode")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionset_directory = QtWidgets.QAction(MainWindow)
        self.actionset_directory.setObjectName("actionset_directory")
        self.actionset_extension = QtWidgets.QAction(MainWindow)
        self.actionset_extension.setObjectName("actionset_extension")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionclear = QtWidgets.QAction(MainWindow)
        self.actionclear.setObjectName("actionclear")
        self.actionsimple_copy = QtWidgets.QAction(MainWindow)
        self.actionsimple_copy.setCheckable(True)
        self.actionsimple_copy.setObjectName("actionsimple_copy")
        self.actioninterpolate = QtWidgets.QAction(MainWindow)
        self.actioninterpolate.setCheckable(True)
        self.actioninterpolate.setObjectName("actioninterpolate")
        self.actionlucas_kanade = QtWidgets.QAction(MainWindow)
        self.actionlucas_kanade.setCheckable(True)
        self.actionlucas_kanade.setChecked(True)
        self.actionlucas_kanade.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionlucas_kanade.setObjectName("actionlucas_kanade")
        self.actiongunner_farnerback = QtWidgets.QAction(MainWindow)
        self.actiongunner_farnerback.setCheckable(True)
        self.actiongunner_farnerback.setObjectName("actiongunner_farnerback")
        self.menuFile.addAction(self.actionset_extension)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuToggle_Duplicate_Mode.addAction(self.actionsimple_copy)
        self.menuToggle_Duplicate_Mode.addAction(self.actioninterpolate)
        self.menuToggle_Duplicate_Mode.addAction(self.actionlucas_kanade)
        self.menuToggle_Duplicate_Mode.addAction(self.actiongunner_farnerback)
        self.menuPreferences.addAction(self.menuToggle_Duplicate_Mode.menuAction())
        self.menuEdit.addAction(self.menuPreferences.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Thib Imave Smoother V0.2"))
        self.PicklePushButton.setText(_translate("MainWindow", "Pickle"))
        self.UnpicklePushButton.setText(_translate("MainWindow", "Unpickle"))
        self.RemovePushButton.setText(_translate("MainWindow", "Remove"))
        self.DuplicatePushButton.setText(_translate("MainWindow", "Duplicate"))
        self.RollbackPushButton.setText(_translate("MainWindow", "RollBack"))
        self.ExtractPushButton.setText(_translate("MainWindow", "Extract"))
        self.showvideoButton.setText(_translate("MainWindow", "Show Video"))
        self.ClearSelectionPushButton.setText(_translate("MainWindow", "Clear Selection"))
        self.picture_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>move cursor to select the image in sequence that you want to work with</p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuPreferences.setTitle(_translate("MainWindow", "Preferences..."))
        self.menuToggle_Duplicate_Mode.setTitle(_translate("MainWindow", "Toggle Duplicate Mode"))
        self.actionset_directory.setText(_translate("MainWindow", "set directory"))
        self.actionset_extension.setText(_translate("MainWindow", "set extension"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionclear.setText(_translate("MainWindow", "clear"))
        self.actionsimple_copy.setText(_translate("MainWindow", "simple copy"))
        self.actioninterpolate.setText(_translate("MainWindow", "interpolate"))
        self.actionlucas_kanade.setText(_translate("MainWindow", "lucas-kanade"))
        self.actiongunner_farnerback.setText(_translate("MainWindow", "gunner-farnerback"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

