# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyVideoWindowQPixmap.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PictureWindow(object):
    def setupUi(self, PictureWindow):
        PictureWindow.setObjectName("PictureWindow")
        PictureWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        PictureWindow.resize(1527, 978)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PictureWindow.sizePolicy().hasHeightForWidth())
        PictureWindow.setSizePolicy(sizePolicy)
        self.CentraWidget = QtWidgets.QWidget(PictureWindow)
        self.CentraWidget.setMinimumSize(QtCore.QSize(1200, 700))
        self.CentraWidget.setObjectName("CentraWidget")
        self.widget = QtWidgets.QWidget(self.CentraWidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1502, 942))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelQpixmap = QtWidgets.QLabel(self.widget)
        self.labelQpixmap.setMinimumSize(QtCore.QSize(1500, 844))
        self.labelQpixmap.setMaximumSize(QtCore.QSize(1500, 844))
        self.labelQpixmap.setText("")
        self.labelQpixmap.setObjectName("labelQpixmap")
        self.verticalLayout.addWidget(self.labelQpixmap)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.previousButton = QtWidgets.QPushButton(self.widget)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout.addWidget(self.previousButton)
        spacerItem2 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.playButton = QtWidgets.QPushButton(self.widget)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.fpsSlider = QtWidgets.QSlider(self.widget)
        self.fpsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fpsSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.fpsSlider.setObjectName("fpsSlider")
        self.horizontalLayout.addWidget(self.fpsSlider)
        self.fpsValueQlabel = QtWidgets.QLabel(self.widget)
        self.fpsValueQlabel.setMinimumSize(QtCore.QSize(20, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.fpsValueQlabel.setFont(font)
        self.fpsValueQlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.fpsValueQlabel.setText("")
        self.fpsValueQlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fpsValueQlabel.setObjectName("fpsValueQlabel")
        self.horizontalLayout.addWidget(self.fpsValueQlabel)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pauseButton = QtWidgets.QPushButton(self.widget)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout.addWidget(self.pauseButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.resumeButton = QtWidgets.QPushButton(self.widget)
        self.resumeButton.setObjectName("resumeButton")
        self.horizontalLayout.addWidget(self.resumeButton)
        spacerItem5 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.nextButton = QtWidgets.QPushButton(self.widget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        spacerItem6 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        PictureWindow.setCentralWidget(self.CentraWidget)
        self.statusBar = QtWidgets.QStatusBar(PictureWindow)
        self.statusBar.setObjectName("statusBar")
        PictureWindow.setStatusBar(self.statusBar)

        self.retranslateUi(PictureWindow)
        QtCore.QMetaObject.connectSlotsByName(PictureWindow)

    def retranslateUi(self, PictureWindow):
        _translate = QtCore.QCoreApplication.translate
        PictureWindow.setWindowTitle(_translate("PictureWindow", "MainWindow"))
        self.previousButton.setText(_translate("PictureWindow", "Previous"))
        self.playButton.setText(_translate("PictureWindow", "Play"))
        self.label.setText(_translate("PictureWindow", " fps"))
        self.pauseButton.setText(_translate("PictureWindow", "Pause"))
        self.resumeButton.setText(_translate("PictureWindow", "Resume"))
        self.nextButton.setText(_translate("PictureWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PictureWindow = QtWidgets.QMainWindow()
    ui = Ui_PictureWindow()
    ui.setupUi(PictureWindow)
    PictureWindow.show()
    sys.exit(app.exec_())

